;this file for FamiTone2 library generated by text2data tool

soundtrack_music_data:
	.byte 2
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256 ; Borosouro
	.word @song1ch0,@song1ch1,@song1ch2,@song1ch3,@song1ch4,307,256 ; It Keeps Happening

@instruments:
	.byte $b0 ;instrument $00
	.word @env2,@env0,@env0
	.byte $00
	.byte $b0 ;instrument $01
	.word @env1,@env0,@env0
	.byte $00
	.byte $b0 ;instrument $02
	.word @env2,@env0,@env0
	.byte $00
	.byte $30 ;instrument $03
	.word @env3,@env0,@env0
	.byte $00

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $c8,$c6,$c4,$c3,$c2,$c1,$02,$c1,$00,$07
@env2:
	.byte $c6,$cb,$ca,$c7,$c4,$c3,$c1,$c0,$00,$07
@env3:
	.byte $c4,$ca,$c9,$c3,$c1,$c0,$00,$05


; Borosouro
@song0ch0:
	.byte $fb,$06
@ref0:
	.byte $82,$4a,$9d,$58,$9d
@ref1:
	.byte $52,$9d,$58,$9d
@song0ch0loop:
	.byte $ff,$04
	.word @ref0
@ref3:
	.byte $52,$9d,$58,$9d
@ref4:
	.byte $4a,$85,$52,$85,$4a,$8d,$4a,$85,$52,$85,$58,$8d
@ref5:
	.byte $4a,$85,$58,$85,$62,$8d,$62,$85,$5a,$85,$54,$8d
	.byte $fd
	.word @song0ch0loop

; Borosouro
@song0ch1:
@ref6:
	.byte $bf
@ref7:
	.byte $bf
@song0ch1loop:
@ref8:
	.byte $84,$32,$85,$39,$3a,$91,$32,$85,$39,$40,$91
@ref9:
	.byte $36,$85,$3d,$44,$91,$45,$3f,$44,$85,$3a,$8d
@ref10:
	.byte $32,$85,$39,$3a,$91,$32,$85,$39,$40,$91
	.byte $ff,$0b
	.word @ref9
	.byte $fd
	.word @song0ch1loop

; Borosouro
@song0ch2:
@ref12:
	.byte $bf
@ref13:
	.byte $bf
@song0ch2loop:
@ref14:
	.byte $bf
@ref15:
	.byte $bf
@ref16:
	.byte $bf
@ref17:
	.byte $bf
	.byte $fd
	.word @song0ch2loop

; Borosouro
@song0ch3:
@ref18:
	.byte $86,$20,$85,$08,$95,$20,$85,$20,$85,$08,$8d
@ref19:
	.byte $20,$85,$08,$95,$20,$85,$20,$85,$08,$8d
@song0ch3loop:
	.byte $ff,$0a
	.word @ref18
	.byte $ff,$0a
	.word @ref19
	.byte $ff,$0a
	.word @ref19
	.byte $ff,$0a
	.word @ref19
	.byte $fd
	.word @song0ch3loop

; Borosouro
@song0ch4:
@ref24:
	.byte $bf
@ref25:
	.byte $bf
@song0ch4loop:
@ref26:
	.byte $bf
@ref27:
	.byte $bf
@ref28:
	.byte $bf
@ref29:
	.byte $bf
	.byte $fd
	.word @song0ch4loop


; It Keeps Happening
@song1ch0:
	.byte $fb,$03
@song1ch0loop:
@ref30:
	.byte $82,$33,$39,$3a,$85,$33,$39,$3a,$85,$33,$39,$3b,$3d,$41,$3d,$3b
	.byte $37,$32,$85,$41,$3b,$39,$33,$32,$85,$33,$41,$40,$85,$40,$85,$3a
	.byte $85
	.byte $fd
	.word @song1ch0loop

; It Keeps Happening
@song1ch1:
@song1ch1loop:
@ref31:
	.byte $80,$1e,$85,$20,$85,$22,$85,$22,$85,$1e,$85,$20,$85,$22,$85,$22
	.byte $85,$1a,$85,$20,$85,$20,$85,$24,$85,$28,$85,$22,$85,$1e,$85,$1a
	.byte $85
	.byte $fd
	.word @song1ch1loop

; It Keeps Happening
@song1ch2:
@song1ch2loop:
@ref32:
	.byte $f9,$85
	.byte $fd
	.word @song1ch2loop

; It Keeps Happening
@song1ch3:
@song1ch3loop:
@ref33:
	.byte $80,$20,$8d,$20,$85,$1a,$85,$20,$8d,$20,$85,$1a,$85,$20,$8d,$20
	.byte $85,$1a,$85,$20,$8d,$20,$85,$1a,$85
	.byte $fd
	.word @song1ch3loop

; It Keeps Happening
@song1ch4:
@song1ch4loop:
@ref34:
	.byte $f9,$85
	.byte $fd
	.word @song1ch4loop
